BoxLayout:
    orientation: 'vertical'
    BoxLayout:
        BoxLayout:
            TextInput:
                text: '34'
            BoxLayout:
                size_hint_x: 0.2
                orientation: 'vertical'
                Button:
                    text: 'Up'
                Button:
                    text: 'Down'
    Button:
        text: 'Convert miles to km'
    Label:
        text: ''
        color: (1, 1, 0, 1)